## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# List here the tasks and the commands for this workflow
# then run `fzz` to start to work.

- name: quick checks
  run: 
    - go fmt ./...
    - gotestsum --format pkgname
  run_on_init: true
  change: 
    - '**/*.go'
    - '**/*.snap'
  ignore: 
    - '**/*.log'

- name: install after checks
  run: 
    # Validate if file .install contains 1 otherwise 
    - if [ -f .tmp/install ]; then go install . && echo "installed latest" ; fi
  change: 
    - '**/*.go'
    - '**/*.snap'
  ignore: 
    - '**/*.log'

- name: git stage changes
  run: git add {{relative_path}}
  change: 
    - '**/*.go'
    - '**/*.snap'
  ignore: 
    - '**/*.log'
