name: Reset Nightly Branch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  reset-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Reset nightly branch
        run: |
          git checkout -B nightly
          git push origin nightly --force

      - name: Generate new hashes
        run: |
          bash scripts/update-nightly-hash.sh nix/package-nightly.nix ".#nightly"
          echo "testing" > foobar.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
