name: Reset Nightly Branch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  reset:
    name: Runner
    runs-on: ubuntu-latest
    steps:
      - name: Reset dev branch to main
        uses: nicksnell/action-reset-repo@main
        with:
          reset_branch: nighlty
