name: Reset Nightly Branch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Reset dev branch to master
        uses: nicksnell/action-reset-repo@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base_branch: main
          reset_branch: nightly
